# Site information
site_name: hazzy
site_author: Kurt Jacobson
site_description: Documentation for hazzy, a modular Gtk3 based LinuxCNC interface written in python.
site_url: https://kurtjacobson.github.io/hazzy/

# Copyright
copyright: Copyright &copy; 2017 - 2018 Kurt Jacobson

# Repository
repo_name: KurtJacobson/hazzy
repo_url: https://github.com/KurtJacobson/hazzy/
edit_uri: ""

# Configuration
theme:
  name: material
  palette:
    primary: grey
    accent: indigo
  feature:
    tabs: true
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Customization
extra:
  social:
    - type: github
      link: https://github.com/KurtJacobson

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false, linenums=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
- Home: index.md
- Installing: installing.md
- Utilities:
  - Status Monitor: utilities/status_monitor.md
- Modules:
  - CamView: modules/video.md
