# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linuxcnc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='linuxcnc.proto',
  package='linuxcnc',
  syntax='proto3',
  serialized_pb=_b('\n\x0elinuxcnc.proto\x12\x08linuxcnc\"8\n\x04Stat\x12\x1a\n\x12min_position_limit\x18\x01 \x01(\x02\x12\x14\n\x0c\x61\x63tive_queue\x18\x02 \x01(\x05\"P\n\x04\x41xis\x12\x1a\n\x12max_position_limit\x18\x01 \x01(\x02\x12\x1a\n\x12min_position_limit\x18\x02 \x01(\x02\x12\x10\n\x08velocity\x18\x03 \x01(\x02\"\xc4\x03\n\x05Joint\x12\x11\n\tjointType\x18\x01 \x01(\x05\x12\x10\n\x08\x62\x61\x63klash\x18\x02 \x01(\x02\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x05\x12\r\n\x05\x66\x61ult\x18\x04 \x01(\x05\x12\x16\n\x0e\x66\x65rror_current\x18\x05 \x01(\x02\x12\x17\n\x0f\x66\x65rror_highmark\x18\x06 \x01(\x02\x12\r\n\x05homed\x18\x07 \x01(\x05\x12\x0e\n\x06homing\x18\x08 \x01(\x05\x12\r\n\x05inpos\x18\t \x01(\x05\x12\r\n\x05input\x18\n \x01(\x02\x12\x12\n\nmax_ferror\x18\x0b \x01(\x02\x12\x16\n\x0emax_hard_limit\x18\x0c \x01(\x05\x12\x1a\n\x12max_position_limit\x18\r \x01(\x02\x12\x16\n\x0emax_soft_limit\x18\x0e \x01(\x05\x12\x12\n\nmin_ferror\x18\x0f \x01(\x02\x12\x16\n\x0emin_hard_limit\x18\x10 \x01(\x05\x12\x1a\n\x12min_position_limit\x18\x11 \x01(\x02\x12\x16\n\x0emin_soft_limit\x18\x12 \x01(\x05\x12\x0e\n\x06output\x18\x13 \x01(\x02\x12\x17\n\x0foverride_limits\x18\x14 \x01(\x05\x12\r\n\x05units\x18\x15 \x01(\x02\x12\x10\n\x08velocity\x18\x16 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STAT = _descriptor.Descriptor(
  name='Stat',
  full_name='linuxcnc.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_position_limit', full_name='linuxcnc.Stat.min_position_limit', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_queue', full_name='linuxcnc.Stat.active_queue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=84,
)


_AXIS = _descriptor.Descriptor(
  name='Axis',
  full_name='linuxcnc.Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_position_limit', full_name='linuxcnc.Axis.max_position_limit', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_position_limit', full_name='linuxcnc.Axis.min_position_limit', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='linuxcnc.Axis.velocity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=166,
)


_JOINT = _descriptor.Descriptor(
  name='Joint',
  full_name='linuxcnc.Joint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jointType', full_name='linuxcnc.Joint.jointType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backlash', full_name='linuxcnc.Joint.backlash', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='linuxcnc.Joint.enabled', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fault', full_name='linuxcnc.Joint.fault', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ferror_current', full_name='linuxcnc.Joint.ferror_current', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ferror_highmark', full_name='linuxcnc.Joint.ferror_highmark', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='homed', full_name='linuxcnc.Joint.homed', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='homing', full_name='linuxcnc.Joint.homing', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inpos', full_name='linuxcnc.Joint.inpos', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='linuxcnc.Joint.input', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_ferror', full_name='linuxcnc.Joint.max_ferror', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_hard_limit', full_name='linuxcnc.Joint.max_hard_limit', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_position_limit', full_name='linuxcnc.Joint.max_position_limit', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_soft_limit', full_name='linuxcnc.Joint.max_soft_limit', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_ferror', full_name='linuxcnc.Joint.min_ferror', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_hard_limit', full_name='linuxcnc.Joint.min_hard_limit', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_position_limit', full_name='linuxcnc.Joint.min_position_limit', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_soft_limit', full_name='linuxcnc.Joint.min_soft_limit', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='linuxcnc.Joint.output', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='override_limits', full_name='linuxcnc.Joint.override_limits', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='units', full_name='linuxcnc.Joint.units', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='linuxcnc.Joint.velocity', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=621,
)

DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['Axis'] = _AXIS
DESCRIPTOR.message_types_by_name['Joint'] = _JOINT

Stat = _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), dict(
  DESCRIPTOR = _STAT,
  __module__ = 'linuxcnc_pb2'
  # @@protoc_insertion_point(class_scope:linuxcnc.Stat)
  ))
_sym_db.RegisterMessage(Stat)

Axis = _reflection.GeneratedProtocolMessageType('Axis', (_message.Message,), dict(
  DESCRIPTOR = _AXIS,
  __module__ = 'linuxcnc_pb2'
  # @@protoc_insertion_point(class_scope:linuxcnc.Axis)
  ))
_sym_db.RegisterMessage(Axis)

Joint = _reflection.GeneratedProtocolMessageType('Joint', (_message.Message,), dict(
  DESCRIPTOR = _JOINT,
  __module__ = 'linuxcnc_pb2'
  # @@protoc_insertion_point(class_scope:linuxcnc.Joint)
  ))
_sym_db.RegisterMessage(Joint)


# @@protoc_insertion_point(module_scope)
